version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
