import "../styles/globals.css"

import type { Metadata } from "next"
import { Header, ThemeProvider } from "~/components"

export const metadata: Metadata = {
  title: "gametrakr",
  description: "Generated by create next app", // TODO: update description
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
