root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main http"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
log = "air.log"
delay = 500 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
