name: API CI

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/api-cd.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/api-cd.yml"

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0
      - name: Run tests
        run: ./gradlew test
