name: API - Continuous Integration

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: api
    steps:
      - name: Install GO
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Run tests
        run: go test ./... -v -race

  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...

  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Run Golint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false"
