name: Deploy API on AWS EC2

on:
  push:
    branches: [ "setup-api" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build project
      run: ./gradlew build --no-daemon -x test
    - name: Docker Hub sign in
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name:
      run: docker build -t gametrakr/api .
    - name: Push Docker image
      run: docker push gametrakr/api
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull gametrakr/api:latest
      - name: Remove Docker container
        run: docker rm -f gametrakr-api
      - name: Run Docker container
        run: docker run -d -p 80:80 --name gametrakr-api gametrakr/api
