name: Java CI with Gradle

on:
  push:
    branches: [ "setup-api" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: aws-ec2
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew build
