name: Linter
on:
  push:
    branches: [main]
    paths: ["web/**"]
  pull_request:
    branches: [main]
    paths: ["web/**"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install
      - name: Run Eslint + Prettier
        run: bun lint
