name: Playwright Tests
on:
  push:
    branches: [main]
    paths: ["web/**"]
  pull_request:
    branches: [main]
    paths: ["web/**"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.0
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bun playwright install --with-deps
      - name: Run Playwright tests
        run: bun playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
