name: Web CI

on:
  push:
    branches: ["main"]
    paths: ["web/**"]
  pull_request:
    branches: ["main"]
    paths: ["web/**"]

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.0.0]
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install dependencies
        run: bun install
      - name: Install Playwright browsers
        run: bun playwright install --with-deps
      - name: Typecheck
        run: bun run typecheck
      - name: Lint
        run: bun run lint
      - name: Run unit / component tests
        run: bun run test:unit
      - name: Run Playwright tests
        run: bun run test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
